# Install PHP with Apache
FROM php:8.2-apache

# Set user variables
ARG UID=1000
ARG GID=1000

# Modify user and group for www-data
RUN groupmod -g ${GID} www-data && usermod -u ${UID} -g www-data www-data

# Install system dependencies, PHP extensions, and enable Apache mod_rewrite
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git curl unzip libzip-dev libicu-dev && \
    docker-php-ext-install pdo pdo_mysql zip intl && \
    a2enmod rewrite && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Xdebug and set its configuration
RUN pecl install xdebug && docker-php-ext-enable xdebug && \
    echo "xdebug.mode = coverage" >> /usr/local/etc/php/php.ini

# Modify PHP configuration
RUN echo "memory_limit = -1" >> /usr/local/etc/php/php.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.5.8

# Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

# Install New Relic Agent
# RUN curl -L https://download.newrelic.com/php_agent/release/newrelic-php5-10.11.0.3-linux.tar.gz | tar -C /tmp -zx && \
#     export NR_INSTALL_USE_CP_NOT_LN=1 && \
#     export NR_INSTALL_SILENT=1 && \
#     export NR_INSTALL_KEY="YOUR_NR_KEY" && \
#     /tmp/newrelic-php5-*/newrelic-install install && \
#     rm -rf /tmp/newrelic-php5-* /tmp/nrinstall*

# Set working directory
WORKDIR /var/www/html

# Copy application source and set permissions
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 775 /var/www/html/

# Configure Apache for Symfony
RUN echo '<Directory /var/www/html/public>\n\
    Options Indexes FollowSymLinks\n\
    AllowOverride All\n\
    Require all granted\n\
    DirectoryIndex index.php\n\
</Directory>\n' > /etc/apache2/conf-available/symfony.conf && \
    a2enconf symfony && \
    sed -i 's#/var/www/html#/var/www/html/public#g' /etc/apache2/sites-available/000-default.conf
