version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_HOST: db
      NEW_RELIC_APP_NAME: "Todo"
      NEW_RELIC_LICENSE_KEY: "eu01xx874a59ed7559bf15c2d0efa5febbecNRAL"
      NEW_RELIC_LOG_LEVEL: "info"
      NEW_RELIC_DAEMON_LOG_LEVEL: "info"
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: todo
      MYSQL_PASSWORD: password

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  newrelic-infra:
    image: newrelic/infrastructure:latest
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "eu01xx874a59ed7559bf15c2d0efa5febbecNRAL"

volumes:
  db_data: {}
