version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    env_file:
      - .env.local
    depends_on:
      - database
      - mailhog

  database:
    image: mysql:5.7
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - 3310:3306
    env_file:
      - .env.local

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  # newrelic-infra:
  #   image: newrelic/infrastructure:latest
  #   network_mode: host
  #   pid: host
  #   privileged: true
  #   volumes:
  #     - "/:/host:ro"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   env_file:
  #     - .env.local

volumes:
  database_data: {}
